name: Build Flacon for Windows

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Qt
      run: |
        choco install qt5 --version=5.15.2
        set PATH=%PATH%;C:\Qt\5.15.2\msvc2019_64\bin

    - name: Install dependencies
      run: |
        choco install mingw --version=8.1.0
        choco install cmake

    - name: Build
      run: |
        mkdir build
        cd build
        cmake .. -G "Ninja"
        cmake --build . --config Release

    - name: Package
      run: |
        mkdir release
        cp -r build/Release/* release/

    - name: Upload Release Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flacon-release
        path: release/
